### ISSUE TITLE
Only search pages with parent X?

### ISSUE THREAD

**Issue by orschiro** [duyngha/wp-nice-search#14]
Dear @duyngha,

Would it be possible to only search sub-pages that have a specific page parent X?

Thankfully,

~Robert

**Comment by duyngha** [comment]
Hi @orschiro,
It's impossible in this version.
Thanks,
Duy

**Comment by orschiro** [comment]
Hi Duy, 

Thanks for your response!

Do you have any plans on adding this in a future release? 

Warmly,

~Robert

**Comment by duyngha** [comment]
Hi @orschiro,
I'm building a big update in next version 1.1.0. I will consider this function. If it's necessary for users I will integrate it. Thank you very much for your suggestion.
Thanks and Regards,
Duy

**Comment by orschiro** [comment]
That's great to hear, @duyngha!

I thank you. :+1: 

~Robert
