### ISSUE TITLE
Parse error: syntax error, unexpected '[' 

### ISSUE THREAD

**Issue by orschiro** [duyngha/wp-nice-search#9]
Dear @duyngha,

Thank you so much for this great plugin!

I wanted to use it to add a search form to a page to have a searchable database interface for our visitors. 

I added `[wpns_search_form]` to the page but when trying the search form, it shows me the following error:

```
Parse error: syntax error, unexpected '[' in /home/scorai5/public_html/wp-content/plugins/wp-nice-search/src/core/Results/Results.php on line 188
```
![image](https://cloud.githubusercontent.com/assets/170947/12422697/83f73f90-bec8-11e5-986a-e94305941aac.png)

Do you have any idea what might be causing the issue?

Thankfully,

~Robert

**Comment by duyngha** [comment]
Hi Robert

Thanks for using my plugin. I fixed this error. You may pull the updates.

Thanks,
Duy

**Comment by orschiro** [comment]
Hi @duyngha,

Thank you so much for your support!

Is `1.0.7` the new version?

![image](https://cloud.githubusercontent.com/assets/170947/12474421/6158c248-c01b-11e5-84cc-e499b6cad986.png)

~Robert

**Comment by duyngha** [comment]
Hi @orschiro

It's still 1.0.7. You just need remove and install it again to get adjustments. Don't forget save your settings in settings page :).

Thanks,
Regards

**Comment by orschiro** [comment]
Dear @duyngha,

Thank you so much! I just downloaded the latest code as `zip` and uploaded it. 

It is working great! :)

~Robert

**Comment by duyngha** [comment]
you are welcome, @orschiro :)
